### ISSUE TITLE
Supports .phpversion

### ISSUE THREAD

**Issue by vincentchalamon** [wilmoore/php-version#57]
Hi,
Thanks for this useful tool :-)
I wonder an improvement: as a lazy developer, I would find very useful to change automatically PHP version used in my project based on a `.phpversion` file included in it. For example, if my project handles a `.phpversion` file with `5.6` written in it, it will automatically apply `php-version 5.6` when I enter this directory.
I don't know if I'm in the right place for this question, any comments are welcome :-)
Thanks

**Comment by wilmoore** [comment]
Hi @vincentchalamon - Thanks for using this. Rather than bloating this tool with such a feature, I'd highly recommend using [direnv](https://direnv.net) to switch versions.

You'll need to create a custom `~/.direnvrc` file to support the `.php-version` file. The following article will get you going...just swap all the ruby concepts with php concepts:

http://tooky.co.uk/using-direnv-and-chruby-together

Alternatively, you can contribute a direnv stdlib function like the one for Node.js:
https://github.com/direnv/direnv/blob/0f803e6a42325f08f0291a78f79f973a5f01f488/stdlib.sh#L466-L529

Best of luck and definitely let me know how things work out.

**Comment by vincentchalamon** [comment]
Wow, thank you so much for this wonderful resource :-) Works perfectly with following function (in my `~/.direnvrc` file):
```
# use php [version]
use_php() {
  local ver=$1
  if [[ -z $ver ]] && [[ -f .php-version ]]; then
    ver=$(cat .php-version)
  fi
  if [[ -z $ver ]]; then
    echo Unknown php version
    exit 1
  fi
  source $(brew --prefix php-version)/php-version.sh && php-version $ver
}
```

Then, I created a `.envrc` file in my project with the PHP version I want to use for current project: `use php 5.6`

Thank you !!!

**Comment by wilmoore** [comment]
Awesome! When I have some free time, I'll definitely try to port this over to a direnv stdlib function...if you don't beat me to it 😃

**Comment by wilmoore** [comment]
https://github.com/direnv/direnv/issues/250
